//! `Bun.hash` non-cryptographic hash cores, ported bit-for-bit from the Zig standard library
//! (`lib/std/hash/*`) as consumed by Bun v1.2.21's `HashObject` (`src/bun.js/api/HashObject.zig`).
//!
//! Every function is verified against an oracle matrix captured from Bun 1.2.21
//! (`tests/fixtures/bun_hash_oracle.txt`, generated by `gen_bun_hash_oracle.js` next to it); the
//! tests at the bottom replay the full matrix. Hand-rolled integer math only — no external
//! crates (lumen std-only policy).
//!
//! Seed semantics match Bun's `hashWrap`: the JS seed is coerced to `u64`
//! (`toUInt64NoTruncate`, done in `js/bun.js`) then truncated to each hasher's seed width:
//! - `wyhash`, `cityHash64`, `xxHash64`, `murmur64v2`, `rapidhash`: full `u64` seed.
//! - `xxHash32`, `murmur32v2`, `murmur32v3`: `u32` seed (low 32 bits).
//! - `xxHash3`: `u32` seed (low 32 bits), zero-extended into XXH3's `u64` seed — Bun's wrapper
//!   narrows to `u32` first, so the high seed bits never reach the algorithm.
//! - `cityHash32`: seed ignored (Zig's `CityHash32` has no `hashWithSeed`).
//!
//! Return types (mapped in `js/bun.js`): 64-bit families return a JS `bigint`, 32-bit families a
//! JS `number` — exactly Bun's split.

use lumen_host::{Ctx, Value};

// ---- little-endian reads ----------------------------------------------------------------------

#[inline]
fn r32(d: &[u8], o: usize) -> u32 {
    u32::from_le_bytes(d[o..o + 4].try_into().unwrap())
}
#[inline]
fn r64(d: &[u8], o: usize) -> u64 {
    u64::from_le_bytes(d[o..o + 8].try_into().unwrap())
}

// ================================================================================================
// Wyhash (final v4.2 variant) — std/hash/wyhash.zig
// ================================================================================================

mod wy {
    use super::{r32, r64};

    const SECRET: [u64; 4] = [
        0xa0761d6478bd642f,
        0xe7037ed1a0b428db,
        0x8ebc6af09c88c6e3,
        0x589965cc75374cc3,
    ];

    #[inline]
    fn mum(a: &mut u64, b: &mut u64) {
        let x = (*a as u128).wrapping_mul(*b as u128);
        *a = x as u64;
        *b = (x >> 64) as u64;
    }
    #[inline]
    fn mix(a: u64, b: u64) -> u64 {
        let (mut a, mut b) = (a, b);
        mum(&mut a, &mut b);
        a ^ b
    }

    /// `smallKey` (len <= 16): the (a, b) lanes fed straight to final2.
    #[inline]
    fn small_key(input: &[u8]) -> (u64, u64) {
        let len = input.len();
        if len >= 4 {
            let end = len - 4;
            let quarter = (len >> 3) << 2;
            let a = ((r32(input, 0) as u64) << 32) | (r32(input, quarter) as u64);
            let b = ((r32(input, end) as u64) << 32) | (r32(input, end - quarter) as u64);
            (a, b)
        } else if len > 0 {
            (
                ((input[0] as u64) << 16)
                    | ((input[len >> 1] as u64) << 8)
                    | (input[len - 1] as u64),
                0,
            )
        } else {
            (0, 0)
        }
    }

    /// One 48-byte round over the three-lane state.
    #[inline]
    fn round(state: &mut [u64; 3], input: &[u8], base: usize) {
        for (j, lane) in state.iter_mut().enumerate() {
            let a = r64(input, base + 16 * j);
            let b = r64(input, base + 16 * j + 8);
            *lane = mix(a ^ SECRET[j + 1], b ^ *lane);
        }
    }

    pub fn hash(seed: u64, input: &[u8]) -> u64 {
        let s0 = seed ^ mix(seed ^ SECRET[0], SECRET[1]);
        let mut state = [s0, s0, s0];
        let len = input.len();

        let (mut a, mut b);
        if len <= 16 {
            (a, b) = small_key(input);
        } else {
            let mut i = 0usize;
            if len >= 48 {
                while i + 48 < len {
                    round(&mut state, input, i);
                    i += 48;
                }
                state[0] ^= state[1] ^ state[2]; // final0
            }
            // final1(input, start_pos = i): 16-byte stripes, then the trailing 16 bytes.
            let mut j = i;
            while j + 16 < len {
                state[0] = mix(r64(input, j) ^ SECRET[1], r64(input, j + 8) ^ state[0]);
                j += 16;
            }
            a = r64(input, len - 16);
            b = r64(input, len - 8);
        }

        // final2, total_len = len
        a ^= SECRET[1];
        b ^= state[0];
        mum(&mut a, &mut b);
        mix(a ^ SECRET[0] ^ (len as u64), b ^ SECRET[1])
    }
}

// ================================================================================================
// CityHash32 / CityHash64 — std/hash/cityhash.zig
// ================================================================================================

mod city {
    use super::{r32, r64};

    const C1: u32 = 0xcc9e2d51;
    const C2: u32 = 0x1b873593;

    #[inline]
    fn fmix(h: u32) -> u32 {
        let mut h = h;
        h ^= h >> 16;
        h = h.wrapping_mul(0x85ebca6b);
        h ^= h >> 13;
        h = h.wrapping_mul(0xc2b2ae35);
        h ^= h >> 16;
        h
    }
    #[inline]
    fn mur(a: u32, h: u32) -> u32 {
        let a = a.wrapping_mul(C1).rotate_right(17).wrapping_mul(C2);
        (h ^ a).rotate_right(19).wrapping_mul(5).wrapping_add(0xe6546b64)
    }

    fn hash32_len_0_to_4(s: &[u8]) -> u32 {
        let len = s.len() as u32;
        let mut b: u32 = 0;
        let mut c: u32 = 9;
        for &v in s {
            // Zig sign-extends the byte (i8 -> i32) before the wrapping add.
            b = b.wrapping_mul(C1).wrapping_add(v as i8 as i32 as u32);
            c ^= b;
        }
        fmix(mur(b, mur(len, c)))
    }

    fn hash32_len_5_to_12(s: &[u8]) -> u32 {
        let len = s.len();
        let mut a = len as u32;
        let mut b = a.wrapping_mul(5);
        let mut c: u32 = 9;
        let d = b;
        a = a.wrapping_add(r32(s, 0));
        b = b.wrapping_add(r32(s, len - 4));
        c = c.wrapping_add(r32(s, (len >> 1) & 4));
        fmix(mur(c, mur(b, mur(a, d))))
    }

    fn hash32_len_13_to_24(s: &[u8]) -> u32 {
        let len = s.len();
        let a = r32(s, (len >> 1) - 4);
        let b = r32(s, 4);
        let c = r32(s, len - 8);
        let d = r32(s, len >> 1);
        let e = r32(s, 0);
        let f = r32(s, len - 4);
        fmix(mur(f, mur(e, mur(d, mur(c, mur(b, mur(a, len as u32)))))))
    }

    pub fn hash32(s: &[u8]) -> u32 {
        let n = s.len();
        if n <= 24 {
            if n <= 4 {
                return hash32_len_0_to_4(s);
            } else if n <= 12 {
                return hash32_len_5_to_12(s);
            }
            return hash32_len_13_to_24(s);
        }

        let len = n as u32;
        let mut h = len;
        let mut g = C1.wrapping_mul(len);
        let mut f = g;

        let a0 = r32(s, n - 4).wrapping_mul(C1).rotate_right(17).wrapping_mul(C2);
        let a1 = r32(s, n - 8).wrapping_mul(C1).rotate_right(17).wrapping_mul(C2);
        let a2 = r32(s, n - 16).wrapping_mul(C1).rotate_right(17).wrapping_mul(C2);
        let a3 = r32(s, n - 12).wrapping_mul(C1).rotate_right(17).wrapping_mul(C2);
        let a4 = r32(s, n - 20).wrapping_mul(C1).rotate_right(17).wrapping_mul(C2);

        h ^= a0;
        h = h.rotate_right(19).wrapping_mul(5).wrapping_add(0xe6546b64);
        h ^= a2;
        h = h.rotate_right(19).wrapping_mul(5).wrapping_add(0xe6546b64);
        g ^= a1;
        g = g.rotate_right(19).wrapping_mul(5).wrapping_add(0xe6546b64);
        g ^= a3;
        g = g.rotate_right(19).wrapping_mul(5).wrapping_add(0xe6546b64);
        f = f.wrapping_add(a4).rotate_right(19).wrapping_mul(5).wrapping_add(0xe6546b64);

        let mut iters = (n - 1) / 20;
        let mut p = 0usize;
        while iters != 0 {
            let b0 = r32(s, p).wrapping_mul(C1).rotate_right(17).wrapping_mul(C2);
            let b1 = r32(s, p + 4);
            let b2 = r32(s, p + 8).wrapping_mul(C1).rotate_right(17).wrapping_mul(C2);
            let b3 = r32(s, p + 12).wrapping_mul(C1).rotate_right(17).wrapping_mul(C2);
            let b4 = r32(s, p + 16);

            h ^= b0;
            h = h.rotate_right(18).wrapping_mul(5).wrapping_add(0xe6546b64);
            f = f.wrapping_add(b1).rotate_right(19).wrapping_mul(C1);
            g = g.wrapping_add(b2).rotate_right(18).wrapping_mul(5).wrapping_add(0xe6546b64);
            h ^= b3.wrapping_add(b1);
            h = h.rotate_right(19).wrapping_mul(5).wrapping_add(0xe6546b64);
            g ^= b4;
            g = g.swap_bytes().wrapping_mul(5);
            h = h.wrapping_add(b4.wrapping_mul(5)).swap_bytes();
            f = f.wrapping_add(b0);
            // (h, f, g) = (f, g, h) — the Zig source's three-way swap via temp t.
            let t = h;
            h = f;
            f = g;
            g = t;
            p += 20;
            iters -= 1;
        }
        g = g.rotate_right(11).wrapping_mul(C1);
        g = g.rotate_right(17).wrapping_mul(C1);
        f = f.rotate_right(11).wrapping_mul(C1);
        f = f.rotate_right(17).wrapping_mul(C1);
        h = h.wrapping_add(g).rotate_right(19);
        h = h.wrapping_mul(5).wrapping_add(0xe6546b64);
        h = h.rotate_right(17).wrapping_mul(C1);
        h = h.wrapping_add(f).rotate_right(19);
        h = h.wrapping_mul(5).wrapping_add(0xe6546b64);
        h.rotate_right(17).wrapping_mul(C1)
    }

    // ---- CityHash64 ----
    const K0: u64 = 0xc3a5c85c97cb3127;
    const K1: u64 = 0xb492b66fbe98f273;
    const K2: u64 = 0x9ae16a3b2f90404f;

    #[inline]
    fn shiftmix(v: u64) -> u64 {
        v ^ (v >> 47)
    }
    #[inline]
    fn hash_len_16_mul(low: u64, high: u64, mul: u64) -> u64 {
        let mut a = (low ^ high).wrapping_mul(mul);
        a ^= a >> 47;
        let mut b = (high ^ a).wrapping_mul(mul);
        b ^= b >> 47;
        b.wrapping_mul(mul)
    }
    #[inline]
    fn hash_len_16(u: u64, v: u64) -> u64 {
        hash_len_16_mul(u, v, 0x9ddfea08eb382d69)
    }

    fn hash_len_0_to_16(s: &[u8]) -> u64 {
        let n = s.len();
        let len = n as u64;
        if n >= 8 {
            let mul = K2.wrapping_add(len.wrapping_mul(2));
            let a = r64(s, 0).wrapping_add(K2);
            let b = r64(s, n - 8);
            let c = b.rotate_right(37).wrapping_mul(mul).wrapping_add(a);
            let d = a.rotate_right(25).wrapping_add(b).wrapping_mul(mul);
            return hash_len_16_mul(c, d, mul);
        }
        if n >= 4 {
            let mul = K2.wrapping_add(len.wrapping_mul(2));
            let a = r32(s, 0) as u64;
            return hash_len_16_mul(len.wrapping_add(a << 3), r32(s, n - 4) as u64, mul);
        }
        if n > 0 {
            let a = s[0] as u32;
            let b = s[n >> 1] as u32;
            let c = s[n - 1] as u32;
            let y = a.wrapping_add(b << 8);
            let z = (n as u32).wrapping_add(c << 2);
            return shiftmix((y as u64).wrapping_mul(K2) ^ (z as u64).wrapping_mul(K0))
                .wrapping_mul(K2);
        }
        K2
    }

    fn hash_len_17_to_32(s: &[u8]) -> u64 {
        let n = s.len();
        let len = n as u64;
        let mul = K2.wrapping_add(len.wrapping_mul(2));
        let a = r64(s, 0).wrapping_mul(K1);
        let b = r64(s, 8);
        let c = r64(s, n - 8).wrapping_mul(mul);
        let d = r64(s, n - 16).wrapping_mul(K2);
        hash_len_16_mul(
            a.wrapping_add(b)
                .rotate_right(43)
                .wrapping_add(c.rotate_right(30))
                .wrapping_add(d),
            a.wrapping_add(b.wrapping_add(K2).rotate_right(18)).wrapping_add(c),
            mul,
        )
    }

    fn hash_len_33_to_64(s: &[u8]) -> u64 {
        let n = s.len();
        let len = n as u64;
        let mul = K2.wrapping_add(len.wrapping_mul(2));
        let a = r64(s, 0).wrapping_mul(K2);
        let b = r64(s, 8);
        let c = r64(s, n - 24);
        let d = r64(s, n - 32);
        let e = r64(s, 16).wrapping_mul(K2);
        let f = r64(s, 24).wrapping_mul(9);
        let g = r64(s, n - 8);
        let h = r64(s, n - 16).wrapping_mul(mul);

        let u = a
            .wrapping_add(g)
            .rotate_right(43)
            .wrapping_add(b.rotate_right(30).wrapping_add(c).wrapping_mul(9));
        let v = ((a.wrapping_add(g)) ^ d).wrapping_add(f).wrapping_add(1);
        let w = u.wrapping_add(v).wrapping_mul(mul).swap_bytes().wrapping_add(h);
        let x = e.wrapping_add(f).rotate_right(42).wrapping_add(c);
        let y = v
            .wrapping_add(w)
            .wrapping_mul(mul)
            .swap_bytes()
            .wrapping_add(g)
            .wrapping_mul(mul);
        let z = e.wrapping_add(f).wrapping_add(c);
        let a1 = x
            .wrapping_add(z)
            .wrapping_mul(mul)
            .wrapping_add(y)
            .swap_bytes()
            .wrapping_add(b);
        let b1 = shiftmix(
            z.wrapping_add(a1).wrapping_mul(mul).wrapping_add(d).wrapping_add(h),
        )
        .wrapping_mul(mul);
        b1.wrapping_add(x)
    }

    /// `weakHashLen32WithSeeds` — returns (first, second).
    #[inline]
    fn weak_hash_len_32(s: &[u8], off: usize, a: u64, b: u64) -> (u64, u64) {
        let (w, x, y, z) = (r64(s, off), r64(s, off + 8), r64(s, off + 16), r64(s, off + 24));
        let mut a1 = a.wrapping_add(w);
        let b1 = b.wrapping_add(a1).wrapping_add(z).rotate_right(21);
        let c = a1;
        a1 = a1.wrapping_add(x).wrapping_add(y);
        let b1 = b1.wrapping_add(a1.rotate_right(44));
        (a1.wrapping_add(z), b1.wrapping_add(c))
    }

    fn hash64(s: &[u8]) -> u64 {
        let n = s.len();
        if n <= 32 {
            if n <= 16 {
                return hash_len_0_to_16(s);
            }
            return hash_len_17_to_32(s);
        } else if n <= 64 {
            return hash_len_33_to_64(s);
        }

        let mut len = n as u64;
        let mut x = r64(s, n - 40);
        let mut y = r64(s, n - 16).wrapping_add(r64(s, n - 56));
        let mut z = hash_len_16(r64(s, n - 48).wrapping_add(len), r64(s, n - 24));
        let mut v = weak_hash_len_32(s, n - 64, len, z);
        let mut w = weak_hash_len_32(s, n - 32, y.wrapping_add(K1), x);

        x = x.wrapping_mul(K1).wrapping_add(r64(s, 0));
        len = (len - 1) & !63u64;

        let mut p = 0usize;
        loop {
            x = x
                .wrapping_add(y)
                .wrapping_add(v.0)
                .wrapping_add(r64(s, p + 8))
                .rotate_right(37)
                .wrapping_mul(K1);
            y = y
                .wrapping_add(v.1)
                .wrapping_add(r64(s, p + 48))
                .rotate_right(42)
                .wrapping_mul(K1);
            x ^= w.1;
            y = y.wrapping_add(v.0.wrapping_add(r64(s, p + 40)));
            z = z.wrapping_add(w.0).rotate_right(33).wrapping_mul(K1);
            v = weak_hash_len_32(s, p, v.1.wrapping_mul(K1), x.wrapping_add(w.0));
            w = weak_hash_len_32(s, p + 32, z.wrapping_add(w.1), y.wrapping_add(r64(s, p + 16)));
            std::mem::swap(&mut z, &mut x);
            p += 64;
            len -= 64;
            if len == 0 {
                break;
            }
        }

        hash_len_16(
            hash_len_16(v.0, w.0)
                .wrapping_add(shiftmix(y).wrapping_mul(K1))
                .wrapping_add(z),
            hash_len_16(v.1, w.1).wrapping_add(x),
        )
    }

    /// `hashWithSeed(str, seed)` = `hashLen16(hash(str) -% k2, seed)`.
    pub fn hash64_with_seed(s: &[u8], seed: u64) -> u64 {
        hash_len_16(hash64(s).wrapping_sub(K2), seed)
    }
}

// ================================================================================================
// xxHash32 / xxHash64 — std/hash/xxhash.zig
// ================================================================================================

mod xx {
    use super::{r32, r64};

    const P64_1: u64 = 0x9E3779B185EBCA87;
    const P64_2: u64 = 0xC2B2AE3D27D4EB4F;
    const P64_3: u64 = 0x165667B19E3779F9;
    const P64_4: u64 = 0x85EBCA77C2B2AE63;
    const P64_5: u64 = 0x27D4EB2F165667C5;

    #[inline]
    fn round64(acc: u64, lane: u64) -> u64 {
        acc.wrapping_add(lane.wrapping_mul(P64_2))
            .rotate_left(31)
            .wrapping_mul(P64_1)
    }
    #[inline]
    fn merge64(acc: u64, other: u64) -> u64 {
        (acc ^ round64(0, other)).wrapping_mul(P64_1).wrapping_add(P64_4)
    }
    #[inline]
    fn avalanche64(v: u64) -> u64 {
        let mut r = v ^ (v >> 33);
        r = r.wrapping_mul(P64_2);
        r ^= r >> 29;
        r = r.wrapping_mul(P64_3);
        r ^ (r >> 32)
    }

    /// The tail loop: 8-byte, then 4-byte, then single-byte lanes — exactly the Zig `finalize`
    /// switch unrolled by length class.
    fn finalize64(unfinished: u64, byte_count: usize, d: &[u8], start: usize) -> u64 {
        let plen = d.len() - start;
        let mut acc = unfinished
            .wrapping_add(byte_count as u64)
            .wrapping_add(plen as u64);
        let mut o = start;
        let mut rem = plen;
        while rem >= 8 {
            acc ^= round64(0, r64(d, o));
            acc = acc.rotate_left(27).wrapping_mul(P64_1).wrapping_add(P64_4);
            o += 8;
            rem -= 8;
        }
        if rem >= 4 {
            acc ^= (r32(d, o) as u64).wrapping_mul(P64_1);
            acc = acc.rotate_left(23).wrapping_mul(P64_2).wrapping_add(P64_3);
            o += 4;
            rem -= 4;
        }
        while rem > 0 {
            acc ^= (d[o] as u64).wrapping_mul(P64_5);
            acc = acc.rotate_left(11).wrapping_mul(P64_1);
            o += 1;
            rem -= 1;
        }
        avalanche64(acc)
    }

    pub fn hash64(seed: u64, input: &[u8]) -> u64 {
        if input.len() < 32 {
            return finalize64(seed.wrapping_add(P64_5), 0, input, 0);
        }
        let mut acc1 = seed.wrapping_add(P64_1).wrapping_add(P64_2);
        let mut acc2 = seed.wrapping_add(P64_2);
        let mut acc3 = seed;
        let mut acc4 = seed.wrapping_sub(P64_1);
        let mut i = 0usize;
        while i + 32 <= input.len() {
            acc1 = round64(acc1, r64(input, i));
            acc2 = round64(acc2, r64(input, i + 8));
            acc3 = round64(acc3, r64(input, i + 16));
            acc4 = round64(acc4, r64(input, i + 24));
            i += 32;
        }
        let mut acc = acc1
            .rotate_left(1)
            .wrapping_add(acc2.rotate_left(7))
            .wrapping_add(acc3.rotate_left(12))
            .wrapping_add(acc4.rotate_left(18));
        acc = merge64(acc, acc1);
        acc = merge64(acc, acc2);
        acc = merge64(acc, acc3);
        acc = merge64(acc, acc4);
        finalize64(acc, i, input, i)
    }

    const P32_1: u32 = 0x9E3779B1;
    const P32_2: u32 = 0x85EBCA77;
    const P32_3: u32 = 0xC2B2AE3D;
    const P32_4: u32 = 0x27D4EB2F;
    const P32_5: u32 = 0x165667B1;

    #[inline]
    fn round32(acc: u32, lane: u32) -> u32 {
        acc.wrapping_add(lane.wrapping_mul(P32_2))
            .rotate_left(13)
            .wrapping_mul(P32_1)
    }

    fn finalize32(unfinished: u32, byte_count: usize, d: &[u8], start: usize) -> u32 {
        let plen = d.len() - start;
        let mut acc = unfinished
            .wrapping_add(byte_count as u32)
            .wrapping_add(plen as u32);
        let mut o = start;
        let mut rem = plen;
        while rem >= 4 {
            acc = acc.wrapping_add(r32(d, o).wrapping_mul(P32_3));
            acc = acc.rotate_left(17).wrapping_mul(P32_4);
            o += 4;
            rem -= 4;
        }
        while rem > 0 {
            acc = acc.wrapping_add((d[o] as u32).wrapping_mul(P32_5));
            acc = acc.rotate_left(11).wrapping_mul(P32_1);
            o += 1;
            rem -= 1;
        }
        let mut r = acc ^ (acc >> 15);
        r = r.wrapping_mul(P32_2);
        r ^= r >> 13;
        r = r.wrapping_mul(P32_3);
        r ^ (r >> 16)
    }

    pub fn hash32(seed: u32, input: &[u8]) -> u32 {
        if input.len() < 16 {
            return finalize32(seed.wrapping_add(P32_5), 0, input, 0);
        }
        let mut acc1 = seed.wrapping_add(P32_1).wrapping_add(P32_2);
        let mut acc2 = seed.wrapping_add(P32_2);
        let mut acc3 = seed;
        let mut acc4 = seed.wrapping_sub(P32_1);
        let mut i = 0usize;
        while i + 16 <= input.len() {
            acc1 = round32(acc1, r32(input, i));
            acc2 = round32(acc2, r32(input, i + 4));
            acc3 = round32(acc3, r32(input, i + 8));
            acc4 = round32(acc4, r32(input, i + 12));
            i += 16;
        }
        let acc = acc1
            .rotate_left(1)
            .wrapping_add(acc2.rotate_left(7))
            .wrapping_add(acc3.rotate_left(12))
            .wrapping_add(acc4.rotate_left(18));
        finalize32(acc, i, input, i)
    }
}

// ================================================================================================
// xxHash3, 64-bit — std/hash/xxhash.zig `XxHash3`. The Zig code models the long-input state as an
// 8-lane u64 vector; here it is a plain `[u64; 8]` with the same lane operations.
// ================================================================================================

mod xx3 {
    use super::r64;

    const DEFAULT_SECRET: [u8; 192] = [
        0xb8, 0xfe, 0x6c, 0x39, 0x23, 0xa4, 0x4b, 0xbe, 0x7c, 0x01, 0x81, 0x2c, 0xf7, 0x21, 0xad,
        0x1c, 0xde, 0xd4, 0x6d, 0xe9, 0x83, 0x90, 0x97, 0xdb, 0x72, 0x40, 0xa4, 0xa4, 0xb7, 0xb3,
        0x67, 0x1f, 0xcb, 0x79, 0xe6, 0x4e, 0xcc, 0xc0, 0xe5, 0x78, 0x82, 0x5a, 0xd0, 0x7d, 0xcc,
        0xff, 0x72, 0x21, 0xb8, 0x08, 0x46, 0x74, 0xf7, 0x43, 0x24, 0x8e, 0xe0, 0x35, 0x90, 0xe6,
        0x81, 0x3a, 0x26, 0x4c, 0x3c, 0x28, 0x52, 0xbb, 0x91, 0xc3, 0x00, 0xcb, 0x88, 0xd0, 0x65,
        0x8b, 0x1b, 0x53, 0x2e, 0xa3, 0x71, 0x64, 0x48, 0x97, 0xa2, 0x0d, 0xf9, 0x4e, 0x38, 0x19,
        0xef, 0x46, 0xa9, 0xde, 0xac, 0xd8, 0xa8, 0xfa, 0x76, 0x3f, 0xe3, 0x9c, 0x34, 0x3f, 0xf9,
        0xdc, 0xbb, 0xc7, 0xc7, 0x0b, 0x4f, 0x1d, 0x8a, 0x51, 0xe0, 0x4b, 0xcd, 0xb4, 0x59, 0x31,
        0xc8, 0x9f, 0x7e, 0xc9, 0xd9, 0x78, 0x73, 0x64, 0xea, 0xc5, 0xac, 0x83, 0x34, 0xd3, 0xeb,
        0xc3, 0xc5, 0x81, 0xa0, 0xff, 0xfa, 0x13, 0x63, 0xeb, 0x17, 0x0d, 0xdd, 0x51, 0xb7, 0xf0,
        0xda, 0x49, 0xd3, 0x16, 0x55, 0x26, 0x29, 0xd4, 0x68, 0x9e, 0x2b, 0x16, 0xbe, 0x58, 0x7d,
        0x47, 0xa1, 0xfc, 0x8f, 0xf8, 0xb8, 0xd1, 0x7a, 0xd0, 0x31, 0xce, 0x45, 0xcb, 0x3a, 0x8f,
        0x95, 0x16, 0x04, 0x28, 0xaf, 0xd7, 0xfb, 0xca, 0xbb, 0x4b, 0x40, 0x7e,
    ];

    const PRIME_MX1: u64 = 0x165667919E3779F9;
    const PRIME_MX2: u64 = 0x9FB21C651E98DF25;
    const P64_1: u64 = 0x9E3779B185EBCA87;
    const P64_2: u64 = 0xC2B2AE3D27D4EB4F;
    const P64_3: u64 = 0x165667B19E3779F9;
    const P64_4: u64 = 0x85EBCA77C2B2AE63;
    const P64_5: u64 = 0x27D4EB2F165667C5;
    const P32_1: u64 = 0x9E3779B1;
    const P32_2: u64 = 0x85EBCA77;
    const P32_3: u64 = 0xC2B2AE3D;

    #[inline]
    fn avalanche_h3(x0: u64) -> u64 {
        let x1 = (x0 ^ (x0 >> 37)).wrapping_mul(PRIME_MX1);
        x1 ^ (x1 >> 32)
    }
    #[inline]
    fn avalanche_h64(x0: u64) -> u64 {
        let x1 = (x0 ^ (x0 >> 33)).wrapping_mul(P64_2);
        let x2 = (x1 ^ (x1 >> 29)).wrapping_mul(P64_3);
        x2 ^ (x2 >> 32)
    }
    #[inline]
    fn avalanche_rrmxmx(x0: u64, len: u64) -> u64 {
        let x1 = (x0 ^ x0.rotate_left(49) ^ x0.rotate_left(24)).wrapping_mul(PRIME_MX2);
        let x2 = (x1 ^ ((x1 >> 35).wrapping_add(len))).wrapping_mul(PRIME_MX2);
        x2 ^ (x2 >> 28)
    }
    #[inline]
    fn fold(a: u64, b: u64) -> u64 {
        let wide = (a as u128).wrapping_mul(b as u128);
        (wide as u64) ^ ((wide >> 64) as u64)
    }
    #[inline]
    fn mix16(seed: u64, input: &[u8], in_off: usize, secret: &[u8], sc_off: usize) -> u64 {
        fold(
            r64(input, in_off) ^ r64(secret, sc_off).wrapping_add(seed),
            r64(input, in_off + 8) ^ r64(secret, sc_off + 8).wrapping_sub(seed),
        )
    }

    fn hash3(seed: u64, input: &[u8], secret: &[u8]) -> u64 {
        // len 1..=3
        let len = input.len();
        let flip0 = u32::from_le_bytes(secret[0..4].try_into().unwrap());
        let flip1 = u32::from_le_bytes(secret[4..8].try_into().unwrap());
        let blk = u32::from_le_bytes([input[len - 1], len as u8, input[0], input[len / 2]]);
        let key = ((flip0 ^ flip1) as u64).wrapping_add(seed);
        avalanche_h64(key ^ (blk as u64))
    }

    fn hash8(seed: u64, input: &[u8], secret: &[u8]) -> u64 {
        // len 4..=8
        let len = input.len();
        let flip0 = r64(secret, 8);
        let flip1 = r64(secret, 16);
        let blk0 = u32::from_le_bytes(input[0..4].try_into().unwrap());
        let blk1 = u32::from_le_bytes(input[len - 4..].try_into().unwrap());
        let mixed = seed ^ ((((seed as u32).swap_bytes()) as u64) << 32);
        let key = (flip0 ^ flip1).wrapping_sub(mixed);
        let combined = ((blk0 as u64) << 32).wrapping_add(blk1 as u64);
        avalanche_rrmxmx(key ^ combined, len as u64)
    }

    fn hash16(seed: u64, input: &[u8], secret: &[u8]) -> u64 {
        // len 9..=16
        let len = input.len();
        let lo = r64(input, 0) ^ (r64(secret, 24) ^ r64(secret, 32)).wrapping_add(seed);
        let hi = r64(input, len - 8) ^ (r64(secret, 40) ^ r64(secret, 48)).wrapping_sub(seed);
        let combined = (len as u64)
            .wrapping_add(lo.swap_bytes())
            .wrapping_add(hi)
            .wrapping_add(fold(lo, hi));
        avalanche_h3(combined)
    }

    fn hash128(seed: u64, input: &[u8], secret: &[u8]) -> u64 {
        // len 17..=128
        let len = input.len();
        let mut acc = P64_1.wrapping_mul(len as u64);
        for i in 0..4usize {
            let in_offset = 48 - i * 16;
            let scrt_offset = 96 - i * 32;
            if len > scrt_offset {
                acc = acc.wrapping_add(mix16(seed, input, in_offset, secret, scrt_offset));
                acc = acc.wrapping_add(mix16(
                    seed,
                    input,
                    len - (in_offset + 16),
                    secret,
                    scrt_offset + 16,
                ));
            }
        }
        avalanche_h3(acc)
    }

    fn hash240(seed: u64, input: &[u8], secret: &[u8]) -> u64 {
        // len 129..=240
        let len = input.len();
        let mut acc = P64_1.wrapping_mul(len as u64);
        for i in 0..8usize {
            acc = acc.wrapping_add(mix16(seed, input, i * 16, secret, i * 16));
        }
        let mut acc_end = mix16(seed, input, len - 16, secret, 136 - 17);
        for i in 8..(len / 16) {
            acc_end = acc_end.wrapping_add(mix16(seed, input, i * 16, secret, ((i - 8) * 16) + 3));
        }
        acc = avalanche_h3(acc).wrapping_add(acc_end);
        avalanche_h3(acc)
    }

    // ---- long path (> 240 bytes): 64-byte blocks over an 8-lane state ----

    const LANES: usize = 8;
    const BLOCK: usize = 64; // bytes per block
    const BLOCKS_PER_SCRAMBLE: usize = 1024 / BLOCK; // 16

    /// Per-lane seeded secret: lane j of the 24-lane (192-byte) secret gets `+seed` on even j,
    /// `-seed` on odd j (the Zig vector adds `{seed, -seed, ...}` blockwise; 8 lanes is even, so
    /// the parity is global).
    fn secret_init(seed: u64) -> [u8; 192] {
        let mut out = DEFAULT_SECRET;
        if seed != 0 {
            for j in 0..24usize {
                let add = if j % 2 == 0 { seed } else { seed.wrapping_neg() };
                let v = r64(&DEFAULT_SECRET, j * 8).wrapping_add(add);
                out[j * 8..j * 8 + 8].copy_from_slice(&v.to_le_bytes());
            }
        }
        out
    }

    struct Acc {
        consumed: usize, // blocks consumed since last scramble
        secret: [u8; 192],
        state: [u64; LANES],
    }

    impl Acc {
        fn new(seed: u64) -> Acc {
            Acc {
                consumed: 0,
                secret: secret_init(seed),
                state: [P32_3, P64_1, P64_2, P64_3, P64_4, P32_2, P64_5, P32_1],
            }
        }

        /// One block round: input block at `in_off`, secret window at byte `sc_off`.
        fn round(&mut self, input: &[u8], in_off: usize, sc_off: usize) {
            let mut data = [0u64; LANES];
            for (l, d) in data.iter_mut().enumerate() {
                *d = r64(input, in_off + l * 8);
            }
            for l in 0..LANES {
                let mixed = data[l] ^ r64(&self.secret, sc_off + l * 8);
                self.state[l] = self.state[l]
                    .wrapping_add((mixed & 0xffffffff).wrapping_mul(mixed >> 32));
            }
            // state += shuffle(data, [1,0,3,2,5,4,7,6])
            for l in 0..LANES {
                self.state[l] = self.state[l].wrapping_add(data[l ^ 1]);
            }
        }

        fn accumulate(&mut self, input: &[u8], base: usize, n_blocks: usize) {
            for b in 0..n_blocks {
                self.round(input, base + b * BLOCK, (self.consumed + b) * 8);
            }
        }

        fn scramble(&mut self) {
            let sc_off = 192 - BLOCK;
            for l in 0..LANES {
                let s = r64(&self.secret, sc_off + l * 8);
                self.state[l] ^= self.state[l] >> 47;
                self.state[l] ^= s;
                self.state[l] = self.state[l].wrapping_mul(P32_1);
            }
        }

        fn consume(&mut self, input: &[u8], n_blocks: usize) {
            let mut done = 0usize;
            let mut until = BLOCKS_PER_SCRAMBLE - self.consumed;
            while n_blocks - done >= until {
                self.accumulate(input, done * BLOCK, until);
                self.scramble();
                self.consumed = 0;
                done += until;
                until = BLOCKS_PER_SCRAMBLE;
            }
            let rem = n_blocks - done;
            self.accumulate(input, done * BLOCK, rem);
            self.consumed += rem;
        }

        fn digest(&mut self, total_len: u64, input: &[u8], last_off: usize) -> u64 {
            // The digest round reads a fixed secret window (192 - 64 - 7), not the rolling one.
            let sc_off = 192 - BLOCK - 7;
            self.round(input, last_off, sc_off);
            for l in 0..LANES {
                self.state[l] ^= r64(&self.secret, 11 + l * 8);
            }
            let mut result = P64_1.wrapping_mul(total_len);
            for i in 0..4usize {
                result = result.wrapping_add(fold(self.state[i * 2], self.state[i * 2 + 1]));
            }
            avalanche_h3(result)
        }
    }

    fn hash_long(seed: u64, input: &[u8]) -> u64 {
        let n = input.len();
        let n_blocks = (n - 1) / BLOCK;
        let mut acc = Acc::new(seed);
        acc.consume(input, n_blocks);
        acc.digest(n as u64, input, n - BLOCK)
    }

    pub fn hash(seed: u64, input: &[u8]) -> u64 {
        let secret = &DEFAULT_SECRET;
        let n = input.len();
        if n > 240 {
            return hash_long(seed, input);
        }
        if n > 128 {
            return hash240(seed, input, secret);
        }
        if n > 16 {
            return hash128(seed, input, secret);
        }
        if n > 8 {
            return hash16(seed, input, secret);
        }
        if n > 3 {
            return hash8(seed, input, secret);
        }
        if n > 0 {
            return hash3(seed, input, secret);
        }
        avalanche_h64(seed ^ r64(secret, 56) ^ r64(secret, 64))
    }
}

// ================================================================================================
// Murmur2 (32/64) and Murmur3 (32) — std/hash/murmur.zig. Bun always calls `hashWithSeed`
// (default seed 0 via `hashWrap`), never Zig's 0xc70f6907 default.
// ================================================================================================

mod murmur {
    use super::{r32, r64};

    pub fn murmur2_32(s: &[u8], seed: u32) -> u32 {
        const M: u32 = 0x5bd1e995;
        let len = s.len() as u32;
        let mut h1 = seed ^ len;
        for i in 0..(len >> 2) as usize {
            let mut k1 = r32(s, i * 4).wrapping_mul(M);
            k1 ^= k1 >> 24;
            k1 = k1.wrapping_mul(M);
            h1 = h1.wrapping_mul(M);
            h1 ^= k1;
        }
        let offset = (len & 0xfffffffc) as usize;
        let rest = len & 3;
        if rest >= 3 {
            h1 ^= (s[offset + 2] as u32) << 16;
        }
        if rest >= 2 {
            h1 ^= (s[offset + 1] as u32) << 8;
        }
        if rest >= 1 {
            h1 ^= s[offset] as u32;
            h1 = h1.wrapping_mul(M);
        }
        h1 ^= h1 >> 13;
        h1 = h1.wrapping_mul(M);
        h1 ^ (h1 >> 15)
    }

    pub fn murmur2_64(s: &[u8], seed: u64) -> u64 {
        const M: u64 = 0xc6a4a7935bd1e995;
        let n = s.len();
        let mut h1 = seed ^ (n as u64).wrapping_mul(M);
        for i in 0..n / 8 {
            let mut k1 = r64(s, i * 8).wrapping_mul(M);
            k1 ^= k1 >> 47;
            k1 = k1.wrapping_mul(M);
            h1 ^= k1;
            h1 = h1.wrapping_mul(M);
        }
        let rest = n & 7;
        if rest > 0 {
            let offset = n - rest;
            let mut k1: u64 = 0;
            for (i, &b) in s[offset..].iter().enumerate() {
                k1 |= (b as u64) << (8 * i);
            }
            h1 ^= k1;
            h1 = h1.wrapping_mul(M);
        }
        h1 ^= h1 >> 47;
        h1 = h1.wrapping_mul(M);
        h1 ^ (h1 >> 47)
    }

    pub fn murmur3_32(s: &[u8], seed: u32) -> u32 {
        const C1: u32 = 0xcc9e2d51;
        const C2: u32 = 0x1b873593;
        let len = s.len() as u32;
        let mut h1 = seed;
        for i in 0..(len >> 2) as usize {
            let k1 = r32(s, i * 4).wrapping_mul(C1).rotate_left(15).wrapping_mul(C2);
            h1 ^= k1;
            h1 = h1.rotate_left(13).wrapping_mul(5).wrapping_add(0xe6546b64);
        }
        {
            let mut k1: u32 = 0;
            let offset = (len & 0xfffffffc) as usize;
            let rest = len & 3;
            if rest == 3 {
                k1 ^= (s[offset + 2] as u32) << 16;
            }
            if rest >= 2 {
                k1 ^= (s[offset + 1] as u32) << 8;
            }
            if rest >= 1 {
                k1 ^= s[offset] as u32;
                k1 = k1.wrapping_mul(C1).rotate_left(15).wrapping_mul(C2);
                h1 ^= k1;
            }
        }
        h1 ^= len;
        h1 ^= h1 >> 16;
        h1 = h1.wrapping_mul(0x85ebca6b);
        h1 ^= h1 >> 13;
        h1 = h1.wrapping_mul(0xc2b2ae35);
        h1 ^ (h1 >> 16)
    }
}

// ================================================================================================
// RapidHash — std/hash/RapidHash.zig (rapidhash v1, wyhash-descended)
// ================================================================================================

mod rapid {
    use super::{r32, r64};

    const SECRET: [u64; 3] = [0x2d358dccaa6c78a5, 0x8bb84b93962eacc9, 0x4b33a62ed433d4a3];

    #[inline]
    fn mum(a: &mut u64, b: &mut u64) {
        let r = (*a as u128).wrapping_mul(*b as u128);
        *a = r as u64;
        *b = (r >> 64) as u64;
    }
    #[inline]
    fn mix(a: u64, b: u64) -> u64 {
        let (mut a, mut b) = (a, b);
        mum(&mut a, &mut b);
        a ^ b
    }

    pub fn hash(seed: u64, input: &[u8]) -> u64 {
        let sc = SECRET;
        let len = input.len();
        let mut a: u64 = 0;
        let mut b: u64 = 0;
        let mut is: [u64; 3] = [seed, 0, 0];
        is[0] ^= mix(seed ^ sc[0], sc[1]) ^ (len as u64);

        let mut k = 0usize; // running offset (Zig re-slices `k`)

        if len <= 16 {
            if len >= 4 {
                let d = (len & 24) >> (len >> 3);
                let e = len - 4;
                a = ((r32(input, 0) as u64) << 32) | (r32(input, e) as u64);
                b = ((r32(input, d) as u64) << 32) | (r32(input, e - d) as u64);
            } else if len > 0 {
                a = ((input[0] as u64) << 56)
                    | ((input[len >> 1] as u64) << 32)
                    | (input[len - 1] as u64);
            }
        } else {
            let mut remain = len;
            if len > 48 {
                is[1] = is[0];
                is[2] = is[0];
                while remain >= 96 {
                    for i in 0..6usize {
                        let m1 = r64(input, k + 16 * i);
                        let m2 = r64(input, k + 16 * i + 8);
                        is[i % 3] = mix(m1 ^ sc[i % 3], m2 ^ is[i % 3]);
                    }
                    k += 96;
                    remain -= 96;
                }
                if remain >= 48 {
                    for i in 0..3usize {
                        let m1 = r64(input, k + 16 * i);
                        let m2 = r64(input, k + 16 * i + 8);
                        is[i] = mix(m1 ^ sc[i], m2 ^ is[i]);
                    }
                    k += 48;
                    remain -= 48;
                }
                is[0] ^= is[1] ^ is[2];
            }

            if remain > 16 {
                is[0] = mix(r64(input, k) ^ sc[2], r64(input, k + 8) ^ is[0] ^ sc[1]);
                if remain > 32 {
                    is[0] = mix(r64(input, k + 16) ^ sc[2], r64(input, k + 24) ^ is[0]);
                }
            }

            a = r64(input, len - 16);
            b = r64(input, len - 8);
        }

        a ^= sc[1];
        b ^= is[0];
        mum(&mut a, &mut b);
        mix(a ^ sc[0] ^ (len as u64), b ^ sc[1])
    }
}

// ================================================================================================
// One-shot API (ops + tests)
// ================================================================================================

pub fn wyhash(seed: u64, input: &[u8]) -> u64 {
    wy::hash(seed, input)
}
pub fn city_hash32(input: &[u8]) -> u32 {
    city::hash32(input)
}
pub fn city_hash64(seed: u64, input: &[u8]) -> u64 {
    city::hash64_with_seed(input, seed)
}
pub fn xx_hash32(seed: u32, input: &[u8]) -> u32 {
    xx::hash32(seed, input)
}
pub fn xx_hash64(seed: u64, input: &[u8]) -> u64 {
    xx::hash64(seed, input)
}
pub fn xx_hash3(seed: u32, input: &[u8]) -> u64 {
    xx3::hash(seed as u64, input)
}
pub fn murmur32v3(seed: u32, input: &[u8]) -> u32 {
    murmur::murmur3_32(input, seed)
}
pub fn murmur32v2(seed: u32, input: &[u8]) -> u32 {
    murmur::murmur2_32(input, seed)
}
pub fn murmur64v2(seed: u64, input: &[u8]) -> u64 {
    murmur::murmur2_64(input, seed)
}
pub fn rapidhash(seed: u64, input: &[u8]) -> u64 {
    rapid::hash(seed, input)
}

// ================================================================================================
// Native ops — `__bunhash.<name>(bytes, seed)`. The JS glue normalises the input to a
// Uint8Array and the seed to a `BigInt.asUintN(64, ...)` BigInt before calling; 64-bit families
// come back as a BigInt built from the raw bits (i64 reinterpretation, normalised back to
// unsigned with `BigInt.asUintN(64, ...)` on the JS side), 32-bit families as a Number.
// ================================================================================================

fn arg_bytes(ctx: &mut Ctx, a: &[Value], who: &str) -> Result<Vec<u8>, Value> {
    let v = a.first().unwrap_or(&Value::Undefined);
    ctx.typed_array_bytes(v)
        .ok_or_else(|| ctx.make_error("TypeError", format!("{who} expects a Buffer/TypedArray")))
}

fn arg_seed(a: &[Value]) -> u64 {
    match a.get(1) {
        Some(v) => v
            .bigint_as_i64()
            .map(|x| x as u64)
            .or_else(|| v.as_num_opt().map(|n| n as i64 as u64))
            .unwrap_or(0),
        None => 0,
    }
}

#[inline]
fn u64_big(v: u64) -> Value {
    Value::bigint_from_i64(v as i64)
}

macro_rules! hash_op64 {
    ($name:ident, $who:literal, $call:expr) => {
        pub fn $name(ctx: &mut Ctx, _t: Value, a: &[Value]) -> Result<Value, Value> {
            let bytes = arg_bytes(ctx, a, $who)?;
            let f: fn(u64, &[u8]) -> u64 = $call;
            Ok(u64_big(f(arg_seed(a), &bytes)))
        }
    };
}
macro_rules! hash_op32 {
    ($name:ident, $who:literal, $call:expr) => {
        pub fn $name(ctx: &mut Ctx, _t: Value, a: &[Value]) -> Result<Value, Value> {
            let bytes = arg_bytes(ctx, a, $who)?;
            let f: fn(u32, &[u8]) -> u32 = $call;
            Ok(Value::Num(f(arg_seed(a) as u32, &bytes) as f64))
        }
    };
}

hash_op64!(op_wyhash, "Bun.hash.wyhash", wyhash);
hash_op64!(op_city_hash64, "Bun.hash.cityHash64", city_hash64);
hash_op64!(op_xx_hash64, "Bun.hash.xxHash64", xx_hash64);
hash_op64!(op_murmur64v2, "Bun.hash.murmur64v2", murmur64v2);
hash_op64!(op_rapidhash, "Bun.hash.rapidhash", rapidhash);

hash_op32!(op_xx_hash32, "Bun.hash.xxHash32", xx_hash32);
hash_op32!(op_murmur32v3, "Bun.hash.murmur32v3", murmur32v3);
hash_op32!(op_murmur32v2, "Bun.hash.murmur32v2", murmur32v2);

/// cityHash32 ignores the seed entirely (Bun-observable behavior).
pub fn op_city_hash32(ctx: &mut Ctx, _t: Value, a: &[Value]) -> Result<Value, Value> {
    let bytes = arg_bytes(ctx, a, "Bun.hash.cityHash32")?;
    Ok(Value::Num(city_hash32(&bytes) as f64))
}
/// xxHash3 uses only the low 32 bits of the seed (Bun's wrapper narrows to u32).
pub fn op_xx_hash3(ctx: &mut Ctx, _t: Value, a: &[Value]) -> Result<Value, Value> {
    let bytes = arg_bytes(ctx, a, "Bun.hash.xxHash3")?;
    Ok(u64_big(xx_hash3(arg_seed(a) as u32, &bytes)))
}

// ================================================================================================
// Oracle tests: replay the full matrix captured from Bun 1.2.21.
// ================================================================================================

#[cfg(test)]
mod tests {
    use super::*;

    const ORACLE: &str = include_str!("../tests/fixtures/bun_hash_oracle.txt");

    /// Rebuild an input by its fixture id (rules in the fixture header).
    fn input_bytes(id: &str) -> Vec<u8> {
        fn pat(n: usize) -> Vec<u8> {
            (0..n).map(|i| ((i * 31 + 7) & 0xff) as u8).collect()
        }
        match id {
            "empty" => Vec::new(),
            "k1" => pat(1024),
            "k64" => pat(65536),
            "zero64" => vec![0u8; 64],
            "ff64" => vec![0xffu8; 64],
            "utf8" => "héllo wörld 你好 🌍 café Ⓐ ∑∫ 𝕳𝖊𝖑𝖑𝖔".as_bytes().to_vec(),
            _ => {
                let n: usize = id.strip_prefix("len").expect("known input id").parse().unwrap();
                pat(n)
            }
        }
    }

    fn adler32(data: &[u8]) -> u32 {
        let (mut a, mut s) = (1u32, 0u32);
        for &b in data {
            a = (a + b as u32) % 65521;
            s = (s + a) % 65521;
        }
        (s << 16) | a
    }

    #[test]
    fn oracle_matrix() {
        let mut checked = 0usize;
        let mut by_family: std::collections::BTreeMap<&str, usize> = Default::default();
        for line in ORACLE.lines() {
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let mut parts = line.split('|');
            let family = parts.next().unwrap();
            let seed = u64::from_str_radix(parts.next().unwrap(), 16).unwrap();
            let input_id = parts.next().unwrap();
            let input = input_bytes(input_id);
            let expect_hex = parts.next().unwrap();
            let got: u64 = match family {
                "wyhash" | "default" => wyhash(seed, &input),
                "cityHash32" => city_hash32(&input) as u64,
                "cityHash64" => city_hash64(seed, &input),
                "xxHash32" => xx_hash32(seed as u32, &input) as u64,
                "xxHash64" => xx_hash64(seed, &input),
                "xxHash3" => xx_hash3(seed as u32, &input),
                "murmur32v3" => murmur32v3(seed as u32, &input) as u64,
                "murmur32v2" => murmur32v2(seed as u32, &input) as u64,
                "murmur64v2" => murmur64v2(seed, &input),
                "rapidhash" => rapidhash(seed, &input),
                "crc32" => lumen_host::deflate::crc32_from(0, &input) as u64,
                "adler32" => adler32(&input) as u64,
                other => panic!("unknown oracle family {other}"),
            };
            let expect = u64::from_str_radix(expect_hex, 16).unwrap();
            assert_eq!(
                got, expect,
                "{family} seed={seed:#018x} input={input_id} → got {got:#x}, bun says {expect:#x}"
            );
            checked += 1;
            *by_family.entry(family).or_default() += 1;
        }
        // Every family must actually appear (guards against a truncated fixture).
        for fam in [
            "wyhash", "default", "cityHash32", "cityHash64", "xxHash32", "xxHash64", "xxHash3",
            "murmur32v3", "murmur32v2", "murmur64v2", "rapidhash", "crc32", "adler32",
        ] {
            assert!(by_family.contains_key(fam), "oracle has no rows for {fam}");
        }
        assert!(checked > 10_000, "oracle matrix suspiciously small: {checked}");
    }

    /// Zig stdlib's own wyhash test vectors (upstream wyhash final v4.2 `test_vector.cpp`).
    #[test]
    fn wyhash_upstream_vectors() {
        let vs: [(u64, u64, &str); 7] = [
            (0, 0x0409638ee2bde459, ""),
            (1, 0xa8412d091b5fe0a9, "a"),
            (2, 0x32dd92e4b2915153, "abc"),
            (3, 0x8619124089a3a16b, "message digest"),
            (4, 0x7a43afb61d7f5f40, "abcdefghijklmnopqrstuvwxyz"),
            (5, 0xff42329b90e50d58, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"),
            (
                6,
                0xc39cab13b115aad3,
                "12345678901234567890123456789012345678901234567890123456789012345678901234567890",
            ),
        ];
        for (seed, expect, input) in vs {
            assert_eq!(wyhash(seed, input.as_bytes()), expect, "wyhash({seed}, {input:?})");
        }
    }

    /// Zig stdlib's RapidHash vectors (seed = RAPID_SEED).
    #[test]
    fn rapidhash_upstream_vectors() {
        const RAPID_SEED: u64 = 0xbdd89aa982704029;
        let bytes: Vec<u8> = "abcdefgh".repeat(128).into_bytes();
        let sizes = [0usize, 1, 2, 3, 4, 8, 16, 32, 64, 128, 256, 512, 1024];
        let outcomes: [u64; 13] = [
            0x5a6ef77074ebc84b,
            0xc11328477bc0f5d1,
            0x5644ac035e40d569,
            0x0347080fbf5fcd81,
            0x056b66b8dc802bcc,
            0xb6bf9055973aac7c,
            0xed56d62eead1e402,
            0xc19072d767da8ffb,
            0x89bb40a9928a4f0d,
            0xe0af7c5e7b6e29fd,
            0x9a3ed35fbedfa11a,
            0x4c684b2119ca19fb,
            0x4b575f5bf25600d6,
        ];
        for (n, expect) in sizes.iter().zip(outcomes) {
            assert_eq!(rapidhash(RAPID_SEED, &bytes[..*n]), expect, "rapidhash len {n}");
        }
    }
}
